alias pj='python -m json.tool'
alias nl="sed -E 's/\\\\n/\\n/g'"
alias dnpm='docker run --rm -it -v $(pwd):/var/www -v ~/npm:/npm -u root shinydocker/node bash'
#alias dnode='docker run --rm -it -v $(pwd):/var/www shinydocker/node bash'
alias dnode='docker run --rm -it -w /home/node/project -v $(pwd):/home/node/project docker-registry.healthsparq.com/janus/node-base:1 sh'
alias dtest='docker exec -it $(basename "$PWD" | sed -E "s/-//g")_app_1 sh -c "export NODE_PORT=3001 && bash"'
alias dinspect='docker exec -it $(basename "$PWD" | sed -E "s/-//g")_app_1 sh'
alias dbug='docker exec -it $(basename "$PWD" | sed -E "s/-//g")_app_1 sh'
alias daws='docker run --rm -it -v $(pwd):/mnt -v ~/.aws:/root/.aws --entrypoint="" mesosphere/aws-cli sh'
alias dclojure='docker run --rm -it -v $(pwd):/usr/src/app -v $HOME/.m2:/root/.m2 -w /usr/src/app docker-registry.healthsparq.com/janus/clojure-builder'
alias dlein='docker run --rm -it -v $(pwd):/usr/src/app -v $HOME/.m2:/root/.m2 -w /usr/src/app docker-registry.healthsparq.com/janus/clojure-builder'
alias dpython='docker run --rm -it -w /usr/src/app -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/usr/src/app -v $HOME/.aws:/root/.aws docker-registry.janusplatform.io/janus/python-base bash'
alias dpy2='docker run --rm -it -w /usr/src/app -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/usr/src/app -v $HOME/.aws:/root/.aws docker-registry.healthsparq.com/janus/python-base:python-2 bash'
alias djava='docker run --rm -it -v $(pwd):/usr/src/app -v ~/maven-volume:/root/.m2  -v ~/gradle-volume:/root/.gradle -w /usr/src/app -e MAVEN_OPTS="-Xms256m -Xmx512m" maven:3-jdk-8 bash'
#alias dbug='docker run --rm -it -v $(pwd):/var/www -p 8080:8080 shinydocker/node bash'
alias dgo='docker run --rm -it -v $(pwd):/project -w /go/src/ golang:1.11'
# 8 to 12 character pronouncable pw with lower, upper, number, symbol, showing pronunciation and asking for user random input for seed
alias pw='apg -n 19 -x 10 -m 10 -M LCNS -t -s -E 0OI1\|'
alias pws='apg -n 19 -x 10 -m 10 -M lcns -t -s -E 0OI1\|'
alias ll='ls -lh -FG'
alias vimclean='find ./ -name "*.swp" | xargs rm'
#alias awslogin='aws-adfs login --adfs-host aws-sso.cambiahealth.com --authfile=~/.aws/authfile --profile '
alias awslogin='export username=$(janus-keyring janus_cli_adfs_user); export password=$(janus-keyring janus_cli_adfs_password); aws-adfs login --adfs-host aws-sso.cambiahealth.com --env --profile '
alias awsall='awslogin dev && awslogin uat && awslogin prd && awslogin tools && awslogin tools-dev && awslogin default'
alias awsclean='aws-adfs reset --profile '
alias tcurl='curl -u "$(janus-keyring janus_cli_artifactory_user):$(janus-keyring janus_cli_artifactory_api_key)"'
