alias pw='apg -n 19 -x 10 -m 10 -M LCNS -t -s -E 0OI1\|'
alias pws='apg -n 19 -x 10 -m 10 -M lcns -t -s -E 0OI1\|'
alias ll='ls -lh -FG'
alias gcurl='curl -u figadore:$(kr github-pat) '
alias tf='terraform'
